### ISSUE TITLE
Have API to document which colors reference other colors

### ISSUE THREAD

**Issue by JohnAlbin** [JohnAlbin/chroma#1]
Many, many times you'll have one color set to another color. And, if you are about to change a specific color, it would be super handy to be able to get a list of all the other colors that will change if you change this color.

For example:

```
$body-text: #666;
// later in the page...
$button-text: $body-text;
$button-border: $button-text;
$more-link: $body-text;
```

If you were using Color Maps, it would be nice to have a function that returns a list of colors that are referencing the given color name. Something like `gimme-referenced-color(body-text)` would return a list `('button-text', 'more-link')`.

**Comment by JohnAlbin** [comment]
Mostly fixed in 1.0.0-alpha.5.

This bit still doesn't work:

```scss
// Set which color scheme should be used by default when calling the color()
// function.
$chroma-active-scheme: 'functional';

.example-ruleset a {
  // Outputs #0e71b8.
  color: color(link);

  .alternate-color-section & {
    // Outputs #c00.
    color: color(link, alternate);
    // @TODO: Whoops! This doesn't work yet because it finds the "link" color
    // value in the functional color scheme and never sees that the primary
    // color has changed.
  }
}
```
